'use client'

import React, { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Building2, ArrowLeft, CheckCircle } from 'lucide-react'
import StationPartnershipForm from '@/components/station-partnership/StationPartnershipForm'
import { useRouter } from 'next/navigation'

export default function RequestCreationPage() {
  const router = useRouter()
  const [showSuccess, setShowSuccess] = useState(false)
  const [requestNumber, setRequestNumber] = useState('')

  const handleFormSuccess = (data: any) => {
    // Use the request number from the form submission (already generated by StationPartnershipService)
    const requestNum = data.requestNumber;

    // Save to localStorage
    const requestData = {
      requestNumber: requestNum,
      ...data,
      submittedAt: new Date().toISOString(),
      status: 'pending'
    }

    localStorage.setItem(`request-${requestNum}`, JSON.stringify(requestData))

    // Show success message
    setRequestNumber(requestNum)
    setShowSuccess(true)
  }

  const handleBackClick = () => {
    router.push('/station-partnership')
  }

  if (showSuccess) {
    return (
      <div className="min-h-screen relative bg-black">
        {/* Background */}
        <div className="fixed inset-0 z-0">
          <div className="absolute inset-0 bg-gradient-to-br from-green-900/20 via-black/80 to-green-950/20" />
          <div className="absolute inset-0 opacity-20" style={{
            backgroundImage: `
              linear-gradient(rgba(34, 197, 94, 0.1) 1px, transparent 1px),
              linear-gradient(90deg, rgba(34, 197, 94, 0.1) 1px, transparent 1px)
            `,
            backgroundSize: '100px 100px'
          }} />
        </div>

        <div className="relative z-10">
          {/* Navigation */}
          <nav className="bg-black/80 backdrop-blur-md border-b border-white/10">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center h-16">
                <div className="flex items-center">
                  <h1 className="text-2xl font-bold text-white">
                    Louaj
                  </h1>
                </div>
                <button
                  onClick={handleBackClick}
                  className="text-white hover:text-blue-400 transition-colors font-medium flex items-center gap-2"
                >
                  <ArrowLeft className="h-4 w-4" />
                  Back to Partnership
                </button>
              </div>
            </div>
          </nav>

          {/* Success Section */}
          <section className="py-20 px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto text-center">
              <div className="bg-white/5 backdrop-blur-sm border border-green-500/30 rounded-xl p-12">
                <div className="w-20 h-20 bg-green-600/20 rounded-full flex items-center justify-center mx-auto mb-6">
                  <CheckCircle className="h-10 w-10 text-green-400" />
                </div>

                <h1 className="text-3xl sm:text-4xl font-bold text-white mb-4">
                  Application Submitted Successfully!
                </h1>

                <div className="bg-green-600/10 border border-green-500/30 rounded-lg p-6 mb-8">
                  <h2 className="text-xl font-semibold text-green-400 mb-2">
                    Your Request Number
                  </h2>
                  <div className="text-4xl font-bold text-white font-mono tracking-wider">
                    {requestNumber}
                  </div>
                  <p className="text-green-400 text-sm mt-2">
                    Please save this number for future reference
                  </p>
                </div>

                <div className="bg-blue-600/10 border border-blue-500/30 rounded-lg p-6 mb-8">
                  <h3 className="text-lg font-semibold text-blue-400 mb-3">
                    What's Next?
                  </h3>
                  <div className="text-gray-300 text-left space-y-2">
                    <p>• Your application is being reviewed by our partnership team</p>
                    <p>• We'll contact you within 2-3 business days</p>
                    <p>• Check your email for updates on your application status</p>
                    <p>• Use your request number to track your application status</p>
                  </div>
                </div>

                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                  <Button
                    onClick={() => {
                      localStorage.setItem('lastRequestNumber', requestNumber)
                      router.push('/station-partnership')
                    }}
                    className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 text-lg font-semibold rounded-lg transition-all duration-200"
                  >
                    <Building2 className="mr-2 h-5 w-5" />
                    Back to Partnership Page
                  </Button>

                  <Button
                    onClick={() => {
                      const requestData = localStorage.getItem(`request-${requestNumber}`)
                      if (requestData) {
                        const blob = new Blob([requestData], { type: 'application/json' })
                        const url = URL.createObjectURL(blob)
                        const a = document.createElement('a')
                        a.href = url
                        a.download = `request-${requestNumber}.json`
                        document.body.appendChild(a)
                        a.click()
                        document.body.removeChild(a)
                        URL.revokeObjectURL(url)
                      }
                    }}
                    variant="outline"
                    className="border-white/20 text-white hover:bg-white/10 px-8 py-3 text-lg font-semibold rounded-lg transition-all duration-200"
                  >
                    Download Application Backup
                  </Button>
                </div>

                <p className="text-gray-400 text-sm mt-6">
                  Need help? Contact our partnership team at partnerships@louaj.tn
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen relative bg-black">
      {/* Background */}
      <div className="fixed inset-0 z-0">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-900/20 via-black/80 to-blue-950/20" />
        <div className="absolute inset-0 opacity-20" style={{
          backgroundImage: `
            linear-gradient(rgba(59, 130, 246, 0.1) 1px, transparent 1px),
            linear-gradient(90deg, rgba(59, 130, 246, 0.1) 1px, transparent 1px)
          `,
          backgroundSize: '100px 100px'
        }} />
      </div>

      <div className="relative z-10">
        {/* Navigation */}
        <nav className="bg-black/80 backdrop-blur-md border-b border-white/10">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center h-16">
              <div className="flex items-center">
                <h1 className="text-2xl font-bold text-white">
                  Louaj
                </h1>
              </div>
              <button
                onClick={handleBackClick}
                className="text-white hover:text-blue-400 transition-colors font-medium flex items-center gap-2"
              >
                <ArrowLeft className="h-4 w-4" />
                Back to Partnership
              </button>
            </div>
          </div>
        </nav>

        {/* Header Section */}
        <section className="py-12 px-4 sm:px-6 lg:px-8">
          <div className="max-w-6xl mx-auto">
            <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-xl p-8 mb-8">
              <div className="flex items-center gap-4 mb-4">
                <div className="w-12 h-12 bg-blue-600/20 rounded-lg flex items-center justify-center">
                  <Building2 className="h-6 w-6 text-blue-400" />
                </div>
                <div>
                  <h1 className="text-2xl sm:text-3xl font-bold text-white">
                    Apply for Station Partnership
                  </h1>
                  <p className="text-gray-400">
                    Fill out the form below to start your partnership application
                  </p>
                </div>
              </div>

              <div className="bg-blue-600/10 border border-blue-500/30 rounded-lg p-4">
                <h3 className="text-blue-400 font-semibold mb-2">Before You Start</h3>
                <ul className="text-gray-300 text-sm space-y-1">
                  <li>• Make sure you have all required documents ready</li>
                  <li>• Check that you meet our partnership requirements</li>
                  <li>• Application review typically takes 2-3 business days</li>
                  <li>• You'll receive a request number to track your application</li>
                </ul>
              </div>
            </div>

            {/* Form Section */}
            <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-xl p-8">
              <StationPartnershipForm onSuccess={handleFormSuccess} />
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}